on:
  push:
    branches-ignore:
      - main
  pull_request:


jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Ubuntu 24.04
            image: quay.io/zathras/ubuntu-systemd:24.04
            initScript: >
              apt install -y git jq python3-requests
    name: ${{ matrix.name }}
    steps:
      - name: Setup podman
        run: sudo apt update && sudo apt install -y podman

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start container
        run: podman run --privileged --name target -d -v $PWD:/root/pyperf:z ${{ matrix.image }}
      
      - name: Initialize ${{ matrix.name }}
        run: podman exec target ${{ matrix.initScript }}

      - name: Checkout test_tools
        run: podman exec target git clone https://github.com/redhat-performance/test_tools-wrappers.git test_tools/

      - name: Run test
        run: podman exec target ./pyperf/pyperf_run --pyperf_benchmarks 2to3,dulwich_log,go --use_pcp 1 --debug
      