on:
  push:
    branches-ignore:
      - main
  pull_request:


jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Amazon Linux 2023
            image: public.ecr.aws/amazonlinux/amazonlinux:2023
            initScript: >
              dnf install -y git jq diffutils tar util-linux
          - name: Ubuntu 24.04
            image: ubuntu:24.04
            initScript: >
              apt update &&
              apt install -y git jq
          - name: CentOS 9
            image: quay.io/centos/centos:stream9
            initScript: >
              dnf install -y git jq util-linux diffutils
          - name: CentOS 10
            image: quay.io/centos/centos:stream10
            initScript: >
              dnf install -y git jq util-linux diffutils
    name: ${{ matrix.name }}
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Initialize ${{ matrix.name }}
        run: ${{ matrix.initScript }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Checkout test_tools
        run: git clone https://github.com/redhat-performance/test_tools-wrappers.git /github/root/test_tools/

      - name: Run test
        run: ./pyperf/pyperf_run
      